### ISSUE TITLE
Attempts to set property after model is deleted/rolled back

### ISSUE THREAD

**Issue by kmiyashiro** [thefrontside/emberx-select#94] opened 2016-02-11 02:33 UTC
On master, if a model's attribute is bound to the value of the select, you set a default value with `selected=true`, and you destroy/rollback a new model, it will trigger a 
```
Uncaught Error: Attempted to handle event didSetProperty` error. 
It's attempting to modify the attribute after the model is set to `deleted.saved`.
```
This does not occur in 2.0.2.

Test case project: https://github.com/kmiyashiro/xselect-example

1. Go to /wombat route
1. Click on "back" link
1. Error in console

**Comment by Robdel12** [comment] 2016-02-15 21:58
Hi @kmiyashiro!

Could I get a stack trace / example code / steps to reproduce?  I'm having trouble replicating this.

**Comment by kmiyashiro** [comment] 2016-02-17 18:34
I'll try reproducing in an isolated test case

**Comment by kmiyashiro** [comment] 2016-02-23 17:08
Sorry, I forgot to mention that I was using the default selection feature (`selected=true`) and that the list was bound to an array.

**Comment by kmiyashiro** [comment] 2016-02-23 17:18
Here's a project that shows the issue. https://github.com/kmiyashiro/xselect-example

1. Go to `/wombat` route
2. Click on "back" link
3. Error in console

**Comment by Robdel12** [comment] 2016-02-28 07:12
This error also pops its head up if you rollback the model and then make a new selection.

**Comment by Robdel12** [comment] 2016-03-07 20:26
Hey @kmiyashiro! Sorry this has taken so long. I do have another question: are you *only* rolling back on newly created records and seeing this error? Or is this an issue when rolling back an existing model?

I also created an issue on Ember Data to get a little more help. If you'd like to follow along: https://github.com/emberjs/data/issues/4209

**Comment by kmiyashiro** [comment] 2016-03-07 20:54
@Robdel12 That's the only time I saw it because I immediately rolled back x-select and used a different method to set the default value.

**Comment by Robdel12** [comment] 2016-03-09 19:18
This should be fixed with the merge of #97. It does _not_ fix rolling back a newly created model and trying to make a new selection since that's not the proper way to work with ember data.

But this does fix the issue of setting the value when the component is tearing down.

**Closed by Robdel12** 2016-03-09 19:18 UTC
Labels: Bug

**Comment by kmiyashiro** [comment] 2016-03-09 21:15
Thanks!

**Comment by Asherlc** [comment] 2016-04-25 18:55
I think this issue extends to another case -- a record that hasn't finished loading. In the case that you iterate over a hasMany relationship in the template, it'll start to render the template while the model is in `root.loading`, and the `_setDefaultValues` will raise a similar error.

**Comment by jrnk** [comment] 2016-08-25 12:40
Experiencing the same as you ( @Asherlc ) on this, did you happen to solve it?

**Comment by Robdel12** [comment] 2016-08-25 14:49
Interesting, can we open another issue to track this? And an ember-twiddle/repo project for these kinds of things are massively beneficial :D
